name: Docker-Compose Build and Deploy

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image using docker-compose
        run: docker-compose build

      - name: Save Docker image as tar
        run: docker save -o frontend.tar frontend:latest
        
      - name: Giving read permission
        run: chmod +r frontend.tar

      - name: Copy frontend to EC2 server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: frontend.tar
          target: /opt/test/

      - name: SSH into EC2 server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Commands to execute on the EC2 server
            sudo docker load -i /opt/test/frontend.tar
            sudo docker stop frontend
            sudo docker rm frontend
            sudo docker run -d --restart unless-stopped --name frontend -p 3000:3000 frontend:latest
            sudo /etc/init.d/nginx reload
